CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Class" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Year" integer NOT NULL,
    CONSTRAINT "PK_Class" PRIMARY KEY ("Id")
);

CREATE TABLE "Colleges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "University" text NOT NULL,
    "Faculty" text NOT NULL,
    CONSTRAINT "PK_Colleges" PRIMARY KEY ("Id")
);

CREATE TABLE "Students" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Legajo" integer NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "EmailAddress" text NOT NULL,
    "CollegeId" integer NOT NULL,
    CONSTRAINT "PK_Students" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Students_Colleges_CollegeId" FOREIGN KEY ("CollegeId") REFERENCES "Colleges" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Assignments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Filename" text NULL,
    "StudentId" integer NOT NULL,
    "ClassId" integer NOT NULL,
    CONSTRAINT "PK_Assignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Assignments_Class_ClassId" FOREIGN KEY ("ClassId") REFERENCES "Class" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Assignments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InfoItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "StudentId" integer NULL,
    CONSTRAINT "PK_InfoItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InfoItems_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id")
);

CREATE INDEX "IX_Assignments_ClassId" ON "Assignments" ("ClassId");

CREATE INDEX "IX_Assignments_StudentId" ON "Assignments" ("StudentId");

CREATE INDEX "IX_InfoItems_StudentId" ON "InfoItems" ("StudentId");

CREATE INDEX "IX_Students_CollegeId" ON "Students" ("CollegeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240616032826_Initial', '6.0.31');

COMMIT;

